### ISSUE TITLE
AWS Glue docker image com.amazonaws.auth.DefaultAWSCredentialsProviderChain does not implement AWSCredentialsProvider error on CREATE TABLE

### ISSUE THREAD

**Issue by JeevaTM** [awslabs/aws-glue-libs#130]
I want to set local AWS Glue development environment. I created Glue Catalog Database.

I created an IAM user with full S3, Glue, Athena access. Granted the IAM user with super permission for Glue Catalog database in AWS Lake Formation.

I started a Glue notebook and ran the following script:

```
  import sys, os
    from awsglue.transforms import *
    from awsglue.utils import getResolvedOptions
    from pyspark.context import SparkContext
    from awsglue.context import GlueContext
    from awsglue.job import Job
    
    sc = SparkContext.getOrCreate()
    glueContext = GlueContext(sc)
    spark = glueContext.spark_session
    job = Job(glueContext)
    
    
    spark.sql("SHOW DATABASES").show()
    
    spark.sql("""
    CREATE TABLE IF NOT EXISTS db.jeeva_demo ( id int, name string )
    location  's3://bucket/warehouse/db/jeeva_demo';
    """)
    
    job.commit()

```
It successfully displayed the databases and created 'jeeva_demo' table in 'db' Glue Catalog database.

Now I wanted to setup same Glue environment locally to start working on it.

I pulled the docker image `amazon/aws-glue-libs:glue_libs_3.0.0_image_01`

Created a local folder `glue`. My test scripts reside in `glue` folder.

I ran the following command to start the Glue image

    docker run -u 0 -it -v /home/jeeva/glue:/home/glue_user/workspace/ -e AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID -e AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY -e AWS_PROFILE=$PROFILE_NAME -e AWS_REGION=$AWS_REGION -e AWS_EC2_METADATA_DISABLED=true -e DISABLE_SSL=true -p 4040:4040 -p 18080:18080 --name glue_pyspark amazon/aws-glue-libs:glue_libs_3.0.0_image_01

I am sitting behind organization firewall so I update Java keystore with `zscaler.crt` and did `update-ca-trust` with `ca-bundle.pem`.

I ran the same script I ran on AWS Glue locally

    import sys, os
    from awsglue.transforms import *
    from awsglue.utils import getResolvedOptions
    from pyspark.context import SparkContext
    from awsglue.context import GlueContext
    from awsglue.job import Job
    
    sc = SparkContext.getOrCreate()
    glueContext = GlueContext(sc)
    spark = glueContext.spark_session
    job = Job(glueContext)
    
    # TO-DO
    df = spark.sql("SHOW DATABASES")
    
    spark.sql("""
    CREATE TABLE IF NOT EXISTS db.jeeva_demo_local ( id int, name string )
    location  's3://bucket/warehouse/db/jeeva_demo_local';
    """)
    
    job.commit()
```
The variable `df` on debug showed the databases I gave IAM user permission in AWS Lake Formation.

Script would run until it is on CREATE TABLE line and throws the error.
```
    22/04/08 12:54:44 ERROR log: Converting exception to MetaException
    Traceback (most recent call last):
      File "/home/glue_user/workspace/check.py", line 19, in <module>
        """)
      File "/home/glue_user/spark/python/pyspark/sql/session.py", line 723, in sql
        return DataFrame(self._jsparkSession.sql(sqlQuery), self._wrapped)
      File "/home/glue_user/spark/python/lib/py4j-0.10.9-src.zip/py4j/java_gateway.py", line 1305, in __call__
      File "/home/glue_user/spark/python/pyspark/sql/utils.py", line 117, in deco
        raise converted from None
    pyspark.sql.utils.AnalysisException: org.apache.hadoop.hive.ql.metadata.HiveException: MetaException(message:Got exception: java.io.IOException Class class com.amazonaws.auth.DefaultAWSCredentialsProviderChain does not implement AWSCredentialsProvider)
```
I assumed this was error due to AWS Java SDK - S3 missing so I added `spark.jars.packages com.amazonaws:aws-java-sdk:1.11.1000` in /home/glue_user/spark/conf/spark-defaults.conf and ran the python script again.

Spark did download the dependencies but I still have the same error. What am I missing here?

Error:
```
    22/04/08 12:54:44 ERROR log: Got exception: java.io.IOException Class class com.amazonaws.auth.DefaultAWSCredentialsProviderChain does not implement AWSCredentialsProvider
    java.io.IOException: Class class com.amazonaws.auth.DefaultAWSCredentialsProviderChain does not implement AWSCredentialsProvider
            at org.apache.hadoop.fs.s3a.S3AUtils.createAWSCredentialProvider(S3AUtils.java:662)
            at org.apache.hadoop.fs.s3a.S3AUtils.createAWSCredentialProviderSet(S3AUtils.java:605)
            at org.apache.hadoop.fs.s3a.S3AFileSystem.initialize(S3AFileSystem.java:260)
            at org.apache.hadoop.fs.FileSystem.createFileSystem(FileSystem.java:3358)
            at org.apache.hadoop.fs.FileSystem.access$200(FileSystem.java:123)
            at org.apache.hadoop.fs.FileSystem$Cache.getInternal(FileSystem.java:3407)
            at org.apache.hadoop.fs.FileSystem$Cache.get(FileSystem.java:3375)
            at org.apache.hadoop.fs.FileSystem.get(FileSystem.java:486)
            at org.apache.hadoop.fs.Path.getFileSystem(Path.java:365)
            at org.apache.hadoop.hive.metastore.Warehouse.getFs(Warehouse.java:105)
            at org.apache.hadoop.hive.metastore.Warehouse.getDnsPath(Warehouse.java:131)
            at org.apache.hadoop.hive.metastore.Warehouse.getDnsPath(Warehouse.java:137)
            at com.amazonaws.glue.catalog.metastore.GlueMetastoreClientDelegate.validateNewTableAndCreateDirectory(GlueMetastoreClientDelegate.java:685)
            at com.amazonaws.glue.catalog.metastore.GlueMetastoreClientDelegate.createTable(GlueMetastoreClientDelegate.java:388)
            at com.amazonaws.glue.catalog.metastore.AWSCatalogMetastoreClient.createTable(AWSCatalogMetastoreClient.java:608)
            at org.apache.hadoop.hive.ql.metadata.Hive.createTable(Hive.java:866)
            at org.apache.hadoop.hive.ql.metadata.Hive.createTable(Hive.java:881)
            at org.apache.spark.sql.hive.client.HiveClientImpl.$anonfun$createTable$1(HiveClientImpl.scala:543)
            at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
            at org.apache.spark.sql.hive.client.HiveClientImpl.$anonfun$withHiveState$1(HiveClientImpl.scala:291)
            at org.apache.spark.sql.hive.client.HiveClientImpl.liftedTree1$1(HiveClientImpl.scala:224)
            at org.apache.spark.sql.hive.client.HiveClientImpl.retryLocked(HiveClientImpl.scala:223)
            at org.apache.spark.sql.hive.client.HiveClientImpl.withHiveState(HiveClientImpl.scala:273)
            at org.apache.spark.sql.hive.client.HiveClientImpl.createTable(HiveClientImpl.scala:541)
            at org.apache.spark.sql.hive.HiveExternalCatalog.$anonfun$createTable$1(HiveExternalCatalog.scala:312)
            at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
            at org.apache.spark.sql.hive.HiveExternalCatalog.withClient(HiveExternalCatalog.scala:105)
            at org.apache.spark.sql.hive.HiveExternalCatalog.createTable(HiveExternalCatalog.scala:270)
            at org.apache.spark.sql.catalyst.catalog.ExternalCatalogWithListener.createTable(ExternalCatalogWithListener.scala:94)
            at org.apache.spark.sql.catalyst.catalog.SessionCatalog.createTable(SessionCatalog.scala:346)
            at org.apache.spark.sql.execution.command.CreateTableCommand.run(tables.scala:166)
            at org.apache.spark.sql.execution.command.ExecutedCommandExec.sideEffectResult$lzycompute(commands.scala:70)
            at org.apache.spark.sql.execution.command.ExecutedCommandExec.sideEffectResult(commands.scala:68)
            at org.apache.spark.sql.execution.command.ExecutedCommandExec.executeCollect(commands.scala:79)
            at org.apache.spark.sql.Dataset.$anonfun$logicalPlan$1(Dataset.scala:229)
            at org.apache.spark.sql.Dataset.$anonfun$withAction$1(Dataset.scala:3724)
            at org.apache.spark.sql.catalyst.QueryPlanningTracker$.withTracker(QueryPlanningTracker.scala:107)
            at org.apache.spark.sql.execution.SQLExecution$.withTracker(SQLExecution.scala:232)
            at org.apache.spark.sql.execution.SQLExecution$.executeQuery$1(SQLExecution.scala:110)
            at org.apache.spark.sql.execution.SQLExecution$.$anonfun$withNewExecutionId$6(SQLExecution.scala:135)
            at org.apache.spark.sql.catalyst.QueryPlanningTracker$.withTracker(QueryPlanningTracker.scala:107)
            at org.apache.spark.sql.execution.SQLExecution$.withTracker(SQLExecution.scala:232)
            at org.apache.spark.sql.execution.SQLExecution$.$anonfun$withNewExecutionId$5(SQLExecution.scala:135)
            at org.apache.spark.sql.execution.SQLExecution$.withSQLConfPropagated(SQLExecution.scala:253)
            at org.apache.spark.sql.execution.SQLExecution$.$anonfun$withNewExecutionId$1(SQLExecution.scala:134)
            at org.apache.spark.sql.SparkSession.withActive(SparkSession.scala:772)
            at org.apache.spark.sql.execution.SQLExecution$.withNewExecutionId(SQLExecution.scala:68)
            at org.apache.spark.sql.Dataset.withAction(Dataset.scala:3722)
            at org.apache.spark.sql.Dataset.<init>(Dataset.scala:229)
            at org.apache.spark.sql.Dataset$.$anonfun$ofRows$2(Dataset.scala:100)
            at org.apache.spark.sql.SparkSession.withActive(SparkSession.scala:772)
            at org.apache.spark.sql.Dataset$.ofRows(Dataset.scala:97)
            at org.apache.spark.sql.SparkSession.$anonfun$sql$1(SparkSession.scala:615)
            at org.apache.spark.sql.SparkSession.withActive(SparkSession.scala:772)
            at org.apache.spark.sql.SparkSession.sql(SparkSession.scala:610)
            at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
            at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
            at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
            at java.lang.reflect.Method.invoke(Method.java:498)
            at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
            at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
            at py4j.Gateway.invoke(Gateway.java:282)
            at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
            at py4j.commands.CallCommand.execute(CallCommand.java:79)
            at py4j.GatewayConnection.run(GatewayConnection.java:238)
            at java.lang.Thread.run(Thread.java:750)
    22/04/08 12:54:44 ERROR log: Converting exception to MetaException
    Traceback (most recent call last):
      File "/home/glue_user/workspace/check.py", line 19, in <module>
        """)
      File "/home/glue_user/spark/python/pyspark/sql/session.py", line 723, in sql
        return DataFrame(self._jsparkSession.sql(sqlQuery), self._wrapped)
      File "/home/glue_user/spark/python/lib/py4j-0.10.9-src.zip/py4j/java_gateway.py", line 1305, in __call__
      File "/home/glue_user/spark/python/pyspark/sql/utils.py", line 117, in deco
        raise converted from None
    pyspark.sql.utils.AnalysisException: org.apache.hadoop.hive.ql.metadata.HiveException: MetaException(message:Got exception: java.io.IOException Class class com.amazonaws.auth.DefaultAWSCredentialsProviderChain does not implement AWSCredentialsProvider)
```

**Comment by xmubeta** [comment]
I hit the same issue. It seems to be related to Class loader for Hive to load credential class. Anyway, I cannot fix it without code, but I do find a workaround:

Create core-site.xml in aws-glue-libs/conf/, replace your AKSK in it.
#cat aws-glue-libs/conf/core-site.xml

<configuration>
     <property>
         <name>fs.s3.impl</name>
         <value>org.apache.hadoop.fs.s3a.S3AFileSystem</value>
         <description>s3a filesystem implementation</description>
     </property>

<property>
  <name>fs.s3a.access.key</name>
  <value>AK</value>
</property>
<property>
  <name>fs.s3a.secret.key</name>
  <value>SK</value>
</property>
</configuration>


Hopefully it works for you.

**Comment by labbedaine** [comment]
@JeevaTM I am facing the same problem. Did you find a resolution?  I will investigate @xmubeta solution but not sure yet how to do that.

**Comment by JeevaTM** [comment]
@labbedaine I used to following Dockerfile content to work with Iceberg tables in Glue. It works pretty well

FROM amazon/aws-glue-libs:glue_libs_3.0.0_image_01
ENV AWS_ACCESS_KEY_ID="redacted"
ENV AWS_SECRET_ACCESS_KEY="redacted"
ENV DISABLE_SSL=true
ENV AWS_CA_BUNDLE="/etc/pki/ca-trust/source/anchors/ca-bundle.pem"

USER 0

COPY . /home/glue_user/workspace/

COPY cred/ca-bundle.pem /etc/pki/ca-trust/source/anchors/
RUN update-ca-trust

COPY cred/zscaler.crt /home/glue_user/
WORKDIR /usr/lib/jvm/java-1.8.0-amazon-corretto.x86_64/jre/lib/security/
RUN keytool -import -keystore ./cacerts -trustcacerts -file /home/glue_user/zscaler.crt -storepass changeit -noprompt

WORKDIR /home/glue_user/spark/jars/
RUN wget https://repo1.maven.org/maven2/software/amazon/awssdk/bundle/2.15.40/bundle-2.15.40.jar
RUN wget https://repo1.maven.org/maven2/org/apache/iceberg/iceberg-spark3-runtime/0.12.0/iceberg-spark3-runtime-0.12.0.jar
RUN wget https://repo1.maven.org/maven2/software/amazon/awssdk/url-connection-client/2.15.40/url-connection-client-2.15.40.jar

WORKDIR /home/glue_user/aws-glue-libs/awsglue/scripts/
RUN cat /home/glue_user/workspace/cred/ca-bundle.pem >> /home/glue_user/.local/lib/python3.7/site-packages/certifi/cacert.pem
RUN cat /home/glue_user/workspace/cred/ca-bundle.pem >> /usr/local/lib/python3.7/site-packages/certifi/cacert.pem

RUN chown -R glue_user /home/glue_user/

WORKDIR /home/glue_user/workspace/

USER 10000

cabundle.pem is Certificate authority and zscaler is my corporate proxy certificate. Update if required.

The jar file version on wget is necessary to work with Icebergs. Unfortunately, you cannot work with Iceberg 0.13.x with the Glue image, it comes with Spark 3.2 but 3.3 is required so if you write to Iceberg from this Image columns will be missing in Glue data catalog, and Athena preview. Quicksight cannot read the Iceberg even with 'query using athena option'.

All of the above goes for AWS Glue as well, not just the image.

I would divert you to use EMR instead, which comes with 0.13.x iceberg support and such.
