### ISSUE TITLE
Getting AWSConnectionUtils error while running create_dynamic_frame_from_catalog

### ISSUE THREAD

**Issue by purnima1612** [awslabs/aws-glue-libs#143]
Hello All, 

I am trying to run glue job locally after connecting it to AWS .

```

from pyspark import SparkContext
from awsglue.context import GlueContext

glueContext = GlueContext(SparkContext.getOrCreate()) 
#inputDF = glueContext.create_dynamic_frame_from_options(connection_type = "s3", connection_options = {"paths": ["s3://glue-test-sandbox/test.json"]}, format = "json")
#inputDF = glueContext.create_dynamic_frame_from_catalog(database="mdm_xxgmdmadm", table_name= "_edqdbdv_app_svc_gartner_com__xxgmdmadm_t10")
inputDF = glueContext.create_dynamic_frame_from_options(connection_type = "oracle", connection_options = connection_oracle11_options)

inputDF.toDF().show()

```

error I am getting is 
```

An error was encountered:
An error occurred while calling o82.getDynamicFrame.
: java.lang.NoClassDefFoundError: Could not initialize class com.amazonaws.services.glue.util.AWSConnectionUtils$
	at com.amazonaws.services.glue.GlueUtility$.getS3Client(GlueUtility.scala:11)
	at com.amazonaws.services.glue.util.JDBCWrapper$.connectionProperties(JDBCUtils.scala:879)
	at com.amazonaws.services.glue.util.JDBCWrapper.connectionProperties$lzycompute(JDBCUtils.scala:671)
	at com.amazonaws.services.glue.util.JDBCWrapper.connectionProperties(JDBCUtils.scala:671)
	at com.amazonaws.services.glue.util.JDBCWrapper.tableDF(JDBCUtils.scala:797)
	at com.amazonaws.services.glue.util.NoCondition$.tableDF(JDBCUtils.scala:85)
	at com.amazonaws.services.glue.util.NoJDBCPartitioner$.tableDF(JDBCUtils.scala:124)
	at com.amazonaws.services.glue.JDBCDataSource.getDynamicFrame(DataSource.scala:863)
	at com.amazonaws.services.glue.DataSource$class.getDynamicFrame(DataSource.scala:97)
	at com.amazonaws.services.glue.SparkSQLDataSource.getDynamicFrame(DataSource.scala:683)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
	at py4j.Gateway.invoke(Gateway.java:282)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.GatewayConnection.run(GatewayConnection.java:238)
	at java.lang.Thread.run(Thread.java:748)

Traceback (most recent call last):
  File "/home/aws-glue-libs/awsglue.zip/awsglue/context.py", line 204, in create_dynamic_frame_from_options
    return source.getFrame(**kwargs)
  File "/home/aws-glue-libs/awsglue.zip/awsglue/data_source.py", line 36, in getFrame
    jframe = self._jsource.getDynamicFrame()
  File "/home/spark-2.4.3-bin-spark-2.4.3-bin-hadoop2.8/python/lib/py4j-0.10.7-src.zip/py4j/java_gateway.py", line 1257, in __call__
    answer, self.gateway_client, self.target_id, self.name)
  File "/home/spark-2.4.3-bin-spark-2.4.3-bin-hadoop2.8/python/lib/pyspark.zip/pyspark/sql/utils.py", line 63, in deco
    return f(*a, **kw)
  File "/home/spark-2.4.3-bin-spark-2.4.3-bin-hadoop2.8/python/lib/py4j-0.10.7-src.zip/py4j/protocol.py", line 328, in get_return_value
    format(target_id, ".", name), value)
py4j.protocol.Py4JJavaError: An error occurred while calling o82.getDynamicFrame.
: java.lang.NoClassDefFoundError: Could not initialize class com.amazonaws.services.glue.util.AWSConnectionUtils$
	at com.amazonaws.services.glue.GlueUtility$.getS3Client(GlueUtility.scala:11)
	at com.amazonaws.services.glue.util.JDBCWrapper$.connectionProperties(JDBCUtils.scala:879)
	at com.amazonaws.services.glue.util.JDBCWrapper.connectionProperties$lzycompute(JDBCUtils.scala:671)
	at com.amazonaws.services.glue.util.JDBCWrapper.connectionProperties(JDBCUtils.scala:671)
	at com.amazonaws.services.glue.util.JDBCWrapper.tableDF(JDBCUtils.scala:797)
	at com.amazonaws.services.glue.util.NoCondition$.tableDF(JDBCUtils.scala:85)
	at com.amazonaws.services.glue.util.NoJDBCPartitioner$.tableDF(JDBCUtils.scala:124)
	at com.amazonaws.services.glue.JDBCDataSource.getDynamicFrame(DataSource.scala:863)
	at com.amazonaws.services.glue.DataSource$class.getDynamicFrame(DataSource.scala:97)
	at com.amazonaws.services.glue.SparkSQLDataSource.getDynamicFrame(DataSource.scala:683)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
	at py4j.Gateway.invoke(Gateway.java:282)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.GatewayConnection.run(GatewayConnection.java:238)
	at java.lang.Thread.run(Thread.java:748)
```

but when running as following 
```
jdbcDF = spark.read \
    .format("jdbc") \
    .option("url", "jdbc:oracle:thin:@//*****************:1521/*****************") \
    .option("dbtable", "***************") \
    .option("user", "xxgmdmadm") \
    .option("password", "***************") \
    .load()
```
its running fine

**Comment by purnima1612** [comment]
can some one please help in this

**Comment by moomindani** [comment]
We apologize for delay.

If you are still facing this issue, could you please try using the Glue official Docker image to see if the issue happens there?
https://aws.amazon.com/blogs/big-data/develop-and-test-aws-glue-version-3-0-jobs-locally-using-a-docker-container/

**Comment by moomindani** [comment]
Please also make sure that you have AWS SDK for Java v1 in your classpath if you want to use your local setup rather than the Docker container.

For now, I resolve this issue, but please feel free to reopen the issue if you still see the issue even after verifying the classpath.

**Comment by DenisMurakhovskiy** [comment]
I still have the same issue

**Comment by moomindani** [comment]
Could you please try using the Glue official Docker image to see if the issue happens there?
https://aws.amazon.com/blogs/big-data/develop-and-test-aws-glue-version-3-0-jobs-locally-using-a-docker-container/

**Comment by DenisMurakhovskiy** [comment]
Thank you for your quick response!
I am using exactly this Glue Docker image. Here is my command to start JupyterLab (Windows):
```
docker run -it -v //c/.....aws:/home/glue_user/.aws -v //c/Users/..../JUPYTER/:/home/glue_user/workspace/jupyter_workspace/ -e AWS_PROFILE="my_profile" -e DISABLE_SSL=true --rm -p 4040:4040 -p 18080:18080 -p 8998:8998 -p 8888:8888 --name glue_jupyter_lab amazon/aws-glue-libs:glue_libs_3.0.0_image_01 /home/glue_user/jupyter/jupyter_start.sh
```
I am getting this
```
starting org.apache.spark.deploy.history.HistoryServer, logging to /home/glue_user/spark/logs/spark-glue_user-org.apache.spark.deploy.history.HistoryServer-x-xxxxxxxx.out
starting java  -cp /home/glue_user/livy/jars/*:/home/glue_user/livy/conf:/home/glue_user/spark/conf:/home/glue_user/spark/conf: org.apache.livy.server.LivyServer, logging to /home/glue_user/livy/logs/livy-glue_user-server.out
SSL Disabled
[I 2022-09-20 14:06:26.303 ServerApp] jupyterlab | extension was successfully linked.
[I 2022-09-20 14:06:26.314 ServerApp] nbclassic | extension was successfully linked.
[I 2022-09-20 14:06:26.315 ServerApp] Writing Jupyter server cookie secret to /home/glue_user/.local/share/jupyter/runtime/jupyter_cookie_secret
[I 2022-09-20 14:06:27.498 ServerApp] sparkmagic | extension was found and enabled by notebook_shim. Consider moving the extension to Jupyter Server's extension paths.
[I 2022-09-20 14:06:27.498 ServerApp] sparkmagic | extension was successfully linked.
[I 2022-09-20 14:06:27.498 ServerApp] notebook_shim | extension was successfully linked.
[W 2022-09-20 14:06:27.523 ServerApp] All authentication is disabled.  Anyone who can connect to this server will be able to run code.
[I 2022-09-20 14:06:27.525 ServerApp] notebook_shim | extension was successfully loaded.
[I 2022-09-20 14:06:27.526 LabApp] JupyterLab extension loaded from /home/glue_user/.local/lib/python3.7/site-packages/jupyterlab
[I 2022-09-20 14:06:27.526 LabApp] JupyterLab application directory is /home/glue_user/.local/share/jupyter/lab
[I 2022-09-20 14:06:27.530 ServerApp] jupyterlab | extension was successfully loaded.
[I 2022-09-20 14:06:27.536 ServerApp] nbclassic | extension was successfully loaded.
[I 2022-09-20 14:06:27.536 ServerApp] sparkmagic extension enabled!
[I 2022-09-20 14:06:27.536 ServerApp] sparkmagic | extension was successfully loaded.
[I 2022-09-20 14:06:27.537 ServerApp] Serving notebooks from local directory: /home/glue_user/workspace/jupyter_workspace
[I 2022-09-20 14:06:27.537 ServerApp] Jupyter Server 1.18.1 is running at:
[I 2022-09-20 14:06:27.537 ServerApp] http://xxxxxxxxxxxxx:8888/lab
[I 2022-09-20 14:06:27.537 ServerApp]  or http://127.0.0.1:8888/lab
[I 2022-09-20 14:06:27.537 ServerApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
```
JupyterLab works fine and I can run this command and get result.
```
def retrieve_tables(database_name):
    session = boto3.session.Session()
    glue_client = session.client("glue")
    response_get_tables = glue_client.get_tables(DatabaseName=database_name)
    return response_get_tables
[table_dict["Name"] for table_dict in retrieve_tables("Name")["TableList"]]
```
Unfortunately, when I run this command, I get an error.
```
my_df = glueContext.create_dynamic_frame.from_catalog(
    database='database_name',
    table_name='table_name')
```
the error I am getting is
```
An error was encountered:
An error occurred while calling o58.getCatalogSource.
: java.lang.ExceptionInInitializerError
	at com.amazonaws.services.glue.GlueContext.getCatalogSource(GlueContext.scala:184)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
	at py4j.Gateway.invoke(Gateway.java:282)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.GatewayConnection.run(GatewayConnection.java:238)
	at java.lang.Thread.run(Thread.java:750)
Caused by: com.amazonaws.SdkClientException: Unable to load region information from any provider in the chain
	at com.amazonaws.regions.AwsRegionProviderChain.getRegion(AwsRegionProviderChain.java:59)
	at com.amazonaws.services.glue.util.EndpointConfig$.getConfig(EndpointConfig.scala:42)
	at com.amazonaws.services.glue.util.AWSConnectionUtils$.<init>(AWSConnectionUtils.scala:38)
	at com.amazonaws.services.glue.util.AWSConnectionUtils$.<clinit>(AWSConnectionUtils.scala)
	... 12 more

Traceback (most recent call last):
  File "/home/glue_user/aws-glue-libs/PyGlue.zip/awsglue/dynamicframe.py", line 625, in from_catalog
    return self._glue_context.create_dynamic_frame_from_catalog(db, table_name, redshift_tmp_dir, transformation_ctx, push_down_predicate, additional_options, catalog_id, **kwargs)
  File "/home/glue_user/aws-glue-libs/PyGlue.zip/awsglue/context.py", line 177, in create_dynamic_frame_from_catalog
    makeOptions(self._sc, additional_options), catalog_id),
  File "/home/glue_user/spark/python/lib/py4j-0.10.9-src.zip/py4j/java_gateway.py", line 1305, in __call__
    answer, self.gateway_client, self.target_id, self.name)
  File "/home/glue_user/spark/python/pyspark/sql/utils.py", line 111, in deco
    return f(*a, **kw)
  File "/home/glue_user/spark/python/lib/py4j-0.10.9-src.zip/py4j/protocol.py", line 328, in get_return_value
    format(target_id, ".", name), value)
py4j.protocol.Py4JJavaError: An error occurred while calling o58.getCatalogSource.
: java.lang.ExceptionInInitializerError
	at com.amazonaws.services.glue.GlueContext.getCatalogSource(GlueContext.scala:184)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
	at py4j.Gateway.invoke(Gateway.java:282)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.GatewayConnection.run(GatewayConnection.java:238)
	at java.lang.Thread.run(Thread.java:750)
Caused by: com.amazonaws.SdkClientException: Unable to load region information from any provider in the chain
	at com.amazonaws.regions.AwsRegionProviderChain.getRegion(AwsRegionProviderChain.java:59)
	at com.amazonaws.services.glue.util.EndpointConfig$.getConfig(EndpointConfig.scala:42)
	at com.amazonaws.services.glue.util.AWSConnectionUtils$.<init>(AWSConnectionUtils.scala:38)
	at com.amazonaws.services.glue.util.AWSConnectionUtils$.<clinit>(AWSConnectionUtils.scala)
	... 12 more
```
I know about this __Caused by: com.amazonaws.SdkClientException: Unable to load region information from any provider in the chain__. I checked region using this command in JupyterLab Other Terminal `sh-4.2$ aws configure list`
I am getting this
```
      Name          Value                    Type          Location
      ----          -----                    ----          --------
   profile          my_profile_name          manual        --profile
access_key          ****************    shared-credentials-file    
secret_key          ****************    shared-credentials-file    
    region          us-east-1          config-file          ~/.aws/config
```
I have few questions: 

- How I can check which role I'm using? For example, I have Glue role. 
- How I can reach out my catalog?
- Can I use Kinesis stream on that Docker container? Right now, I'm using for that catalog "glueContext.create_data_frame.from_catalog".
- Can I use "Magics" as I use that in Glue Studio Notebook an interactive session? I need "%connections" for RDS Aurora PostgreSQL or "%iam_role".
