### ISSUE TITLE
Glue 5.0 artifacts not available

### ISSUE THREAD

**Issue by ava-windsorb** [awslabs/aws-glue-libs#216]
re: https://aws.amazon.com/about-aws/whats-new/2024/12/aws-glue-5-0/

please make the following 5.0 available as was done for 4.0:
- update here: https://docs.aws.amazon.com/glue/latest/dg/aws-glue-programming-etl-libraries.html
- tgz here: https://aws-glue-etl-artifacts.s3.amazonaws.com/
- docker image here: https://hub.docker.com/r/amazon/aws-glue-libs/tags

**Comment by qmg-tmay** [comment]
Will the 5.0 artefacts include the `awsgluedq` modules? There doesn't currently appear to be anyway to install those libraries locally

**Comment by tb102122** [comment]
Is there also any plan to release the docker image for 5.0? https://gallery.ecr.aws/glue/aws-glue-libs

**Comment by ocvagabond-tech** [comment]
Agreed. No possibility of upgrading to Glue 5.0 without the 5.0 image being publicly available.

**Comment by mesnaround** [comment]
Any ETA on this? These images are very helpful for upgrading and development.

**Comment by M0h3eN** [comment]
I guess the Glue team was on a mission to drop that new version by EOY at all costs—even if it meant forgetting to release the actual artifact. Priorities, right? 🚀😂

**Comment by Saziba** [comment]
And PLEASE, for God's sake, consider this for the Docker image:
https://code.visualstudio.com/docs/remote/faq#_can-i-run-vs-code-server-on-older-linux-distributions

**Comment by SmartCo-Ryan** [comment]
As per the comment [here](https://github.com/awslabs/aws-glue-libs/issues/220#issuecomment-2684683762) from @eliu-git, it looks like a Glue 5.0 image is now available: 

> I can see the Glue image 5.0 was released [here](https://hub.docker.com/r/amazon/aws-glue-libs/tags) today.

**Comment by ava-windsorb** [comment]
sweet, just these 2 to go:
- update here: https://docs.aws.amazon.com/glue/latest/dg/aws-glue-programming-etl-libraries.html
- tgz here: https://aws-glue-etl-artifacts.s3.amazonaws.com/

**Comment by eliu-git** [comment]
> Will the 5.0 artefacts include the `awsgluedq` modules? There doesn't currently appear to be anyway to install those libraries locally

Glue docker image 5.0 is released but couldn't find the `awsgluedq` modules.

**Comment by Saziba** [comment]
I couldn't find `awsglue` libraries in the container:

```
$  docker run --rm -it --user=root --entrypoint ""  public.ecr.aws/glue/aws-glue-libs:5.0.0 find / -type d -name aws-glue-libs 2>/dev/null

$
```

```
$  docker run --rm -it --user=root --entrypoint ""  public.ecr.aws/glue/aws-glue-libs:5.0.0 find / -name PyGlue.zip 2>/dev/null

$
```

```
$  docker run --rm -it --user=root --entrypoint ""  public.ecr.aws/glue/aws-glue-libs:5.0.0 python -c 'import awsglue'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'awsglue'

$
```

**Comment by eliu-git** [comment]
> I couldn't find `awsglue` libraries in the container:
> 
> ```
> $  docker run --rm -it --user=root --entrypoint ""  public.ecr.aws/glue/aws-glue-libs:5.0.0 find / -type d -name aws-glue-libs 2>/dev/null
> 
> $
> ```
> 
> ```
> $  docker run --rm -it --user=root --entrypoint ""  public.ecr.aws/glue/aws-glue-libs:5.0.0 find / -name PyGlue.zip 2>/dev/null
> 
> $
> ```
> 
> ```
> $  docker run --rm -it --user=root --entrypoint ""  public.ecr.aws/glue/aws-glue-libs:5.0.0 python -c 'import awsglue'
> Traceback (most recent call last):
>   File "<string>", line 1, in <module>
> ModuleNotFoundError: No module named 'awsglue'
> 
> $
> ```

This is because the docker image has two version of Python which is python 3.9 and 3.11. Only 3.11 has the `awsglue` package. What you need to do is to set your python as 3.11 in your IDE. After it, it should work.

**Comment by lole-elol** [comment]
It seems that in the provided v5 docker image (https://hub.docker.com/r/amazon/aws-glue-libs) 
the PostgreSQL JDBC drivers are not available:

```
25/03/06 10:06:11 INFO DataCatalogWrapper: DataCatalogWrapper: got connection from glue client with name: xxx and type: JDBC
25/03/06 10:06:11 INFO JDBCConnectionWrapper: GLUE_CONNECTIVITY: retrieved connection properties.
25/03/06 10:06:11 INFO JDBCConnectionWrapper: GLUE_CONNECTIVITY: connection schema version: 1.
25/03/06 10:06:11 INFO JDBCConnectionWrapper: GLUE_CONNECTIVITY: got secrets options from secrets manager.
25/03/06 10:06:11 INFO GlueContext: The DataSource in action : com.amazonaws.services.glue.JDBCDataSource
25/03/06 10:06:11 INFO JDBCJobBookmarkUtil$: Skip JDBC Bookmark, Bookmark is not enabled and Bookmark is not paused or transformationContext is empty.
Traceback (most recent call last):
File "file.py", line 60, in <module>
    response = glueContext.create_dynamic_frame.from_options(
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/awsglue/dynamicframe.py", line 609, in from_options
    return self._glue_context.create_dynamic_frame_from_options(connection_type,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/awsglue/context.py", line 244, in create_dynamic_frame_from_options
    return source.getFrame(**kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/awsglue/data_source.py", line 37, in getFrame
    jframe = self._jsource.getDynamicFrame()
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/spark/python/lib/py4j-0.10.9.7-src.zip/py4j/java_gateway.py", line 1322, in __call__
  File "/usr/lib/spark/python/lib/pyspark.zip/pyspark/errors/exceptions/captured.py", line 179, in deco
  File "/usr/lib/spark/python/lib/py4j-0.10.9.7-src.zip/py4j/protocol.py", line 326, in get_return_value
py4j.protocol.Py4JJavaError: An error occurred while calling o224.getDynamicFrame.
: java.lang.ClassNotFoundException: org.postgresql.Driver
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525)
        at java.base/java.lang.Class.forName0(Native Method)
        at java.base/java.lang.Class.forName(Class.java:375)
        at com.amazonaws.services.glue.util.JDBCUtils.loadDriver(JDBCUtils.scala:225)
        at com.amazonaws.services.glue.util.JDBCUtils.loadDriver$(JDBCUtils.scala:223)
        at com.amazonaws.services.glue.util.PostgresUtils$.loadDriver(JDBCUtils.scala:618)
        at com.amazonaws.services.glue.util.JDBCWrapper$.connectionProperties(JDBCUtils.scala:1104)
        at com.amazonaws.services.glue.util.JDBCWrapper.connectionProperties$lzycompute(JDBCUtils.scala:834)
        at com.amazonaws.services.glue.util.JDBCWrapper.connectionProperties(JDBCUtils.scala:834)
        at com.amazonaws.services.glue.util.JDBCWrapper.tableDF(JDBCUtils.scala:969)
        at com.amazonaws.services.glue.util.NoCondition$.tableDF(JDBCUtils.scala:88)
        at com.amazonaws.services.glue.util.NoJDBCPartitioner$.tableDF(JDBCUtils.scala:174)
        at com.amazonaws.services.glue.JDBCDataSource.getDynamicFrame(DataSource.scala:1022)
        at com.amazonaws.services.glue.DataSource.getDynamicFrame(DataSource.scala:95)
        at com.amazonaws.services.glue.DataSource.getDynamicFrame$(DataSource.scala:95)
        at com.amazonaws.services.glue.AbstractSparkSQLDataSource.getDynamicFrame(DataSource.scala:693)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:569)
        at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
        at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:374)
        at py4j.Gateway.invoke(Gateway.java:282)
        at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
        at py4j.commands.CallCommand.execute(CallCommand.java:79)
        at py4j.ClientServerConnection.waitForCommands(ClientServerConnection.java:182)
        at py4j.ClientServerConnection.run(ClientServerConnection.java:106)
        at java.base/java.lang.Thread.run(Thread.java:840)

25/03/06 10:06:11 INFO SparkContext: Invoking stop() from shutdown hook
25/03/06 10:06:11 INFO SparkContext: SparkContext is stopping with exitCode 0.
```

The connection is retrieved from AWS, but the docker image lacks the necessary drivers. I only tested this for Postgres but Isuspect this being the case for other databases as well.

**Comment by dashmug** [comment]
I have a wrapper library for glue ([glue-utils](https://github.com/dashmug/glue-utils)) and it fails using this Glue docker image.

It seems like this docker image is very different from the previous one.

**Comment by khjoshi94** [comment]
Apologies for commenting after the ticket is closed. But I still do not see the 5.0 jar at `https://aws-glue-etl-artifacts.s3.amazonaws.com/` .  What are the recommendations for projects that still rely on the jar ? For e.g. I have a scala maven project which contains the etl code deployed through ci/cd to respective aws environment. I have dependency defined on the glue etl jar with `provided` scope. Even in that case, for my project to compile, I would need the jar hosted at `https://aws-glue-etl-artifacts.s3.amazonaws.com/` else it fails to resolve. Is that still in works or from 5.0 onwards only a docker image is available.

**Comment by walter-business** [comment]
I want to do something like:
```xml
        <dependency>
            <groupId>com.amazonaws</groupId>
            <artifactId>AWSGlueETL</artifactId>
            <version>5.0.0</version>
        </dependency>
```
in my `pom.xml` file. 

The repository is pointing to:
```xml
        <repository>
            <id>aws-glue-etl-artifacts</id>
            <url>https://aws-glue-etl-artifacts.s3.amazonaws.com/release/</url>
        </repository>
```
I would appreciate too if either the version 5 glue library will be published or give us an "receipt" how to deal with it to be able to use the newest spark versions etc.

I am targeting to write a custom glue connector in Java but want to go with the most recent version 5.0.0 and Java 17.

**Comment by M0h3eN** [comment]
Hello team,

Have you had a chance to look into this? 

> Apologies for commenting after the issue is closed. But I still do not see the 5.0 jar at https://aws-glue-etl-artifacts.s3.amazonaws.com/ . What are the recommendations for projects that still rely on the jar ? For e.g. I have a scala maven project which contains the etl code deployed through ci/cd to respective aws environment. I have dependency defined on the glue etl jar with provided scope. Even in that case, for my project to compile, I would need the jar hosted at https://aws-glue-etl-artifacts.s3.amazonaws.com/ else it fails to resolve. Is that still in works or from 5.0 onwards only a docker image is available.

I haven’t found any indication in the Glue 5.0 documentation that the Scala API is deprecated. Could you please confirm whether it’s still supported? We’re receiving numerous security alerts due to the outdated Spark 3.3.0 version, and we need to know if we should begin planning a migration to EMR.

Thank you!
