### ISSUE TITLE
Error in handling --<argument> vs <argument> in getResolvedOptions

### ISSUE THREAD

**Issue by himanshu-pro** [awslabs/aws-glue-libs#22]
Test Case:
```
from awsglue.utils import getResolvedOptions

getResolvedOptions(["--JOB_RUN_ID", "10", "--random", "7"], ["JOB_RUN_ID", "random"])
```
Expectation: 
```
Traceback (most recent call last):
  ...
    getResolvedOptions(["--JOB_RUN_ID", "10", "--random", "7"], ["--JOB_RUN_ID", "random"])
  File "/Users/shuttl/Downloads/PyGlue.zip/awsglue/utils.py", line 77, in getResolvedOptions
RuntimeError: Using reserved arguments --JOB_RUN_ID
```
Actual: 
```
Traceback (most recent call last):
  ...
    getResolvedOptions(["--JOB_RUN_ID", "10", "--random", "7"], ["JOB_RUN_ID", "random"])
  File "/Users/shuttl/Downloads/PyGlue.zip/awsglue/utils.py", line 92, in getResolvedOptions
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/argparse.py", line 1308, in add_argument
    return self._add_action(action)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/argparse.py", line 1682, in _add_action
    self._optionals._add_action(action)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/argparse.py", line 1509, in _add_action
    action = super(_ArgumentGroup, self)._add_action(action)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/argparse.py", line 1322, in _add_action
    self._check_conflict(action)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/argparse.py", line 1460, in _check_conflict
    conflict_handler(action, confl_optionals)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/argparse.py", line 1467, in _handle_conflict_error
    raise ArgumentError(action, message % conflict_string)
argparse.ArgumentError: argument --JOB_RUN_ID: conflicting option string(s): --JOB_RUN_ID
```

Test Case:
```
from awsglue.utils import getResolvedOptions

print getResolvedOptions(["--JOB_RUN_ID", "10", "--random", "7", "----other", "5"], ["--other", "random"])['--other']
```
Expectation:
```
5
```
Actual:
```
Traceback (most recent call last):
  ...
    print getResolvedOptions(["--JOB_RUN_ID", "10", "--random", "7", "----other", "5"], ["--other", "random"])['--other']
KeyError: '--other'
```

Test Case:
```
from awsglue.utils import getResolvedOptions

print getResolvedOptions(["--JOB_RUN_ID", "10", "--random", "7", "----JOB_RUN_ID", "5"], ["--JOB_RUN_ID", "random"])["--JOB_RUN_ID"]
```
Expectation:
```
5
```
Actual:
```
Traceback (most recent call last):
  ...
    print getResolvedOptions(["--JOB_RUN_ID", "dkfjhbvfkdi_dfhjvb_13e_dfhk", "--random", "gtdgk"], ["--JOB_RUN_ID", "random"])
  File "/Users/shuttl/Downloads/PyGlue.zip/awsglue/utils.py", line 77, in getResolvedOptions
RuntimeError: Using reserved arguments --JOB_RUN_ID
```

**Comment by mdelpoz0** [comment]
Good morning,

I get JOB_ID as well as JOB_RUN_ID in next way:

`args = getResolvedOptions(sys.argv, ['TempDir', 'JOB_NAME'])

print ">>>>> TempDir = " + args['TempDir']
print ">>>>> JOB_NAME = " + args['JOB_NAME']
print ">>>>> JOB_ID = " + args['JOB_ID'] # --> Implicit
print ">>>>> JOB_RUN_ID = " + args['JOB_RUN_ID'] # --> Implicit`

As you can see, even though I have not included JOB_ID and JOB_RUN_ID, I'm getting implicity these values, and I can use them without any problem using args['JOB_ID'] and args['JOB_RUN_ID']

Hope this helps
Mario

**Comment by himanshu-pro** [comment]
> Good morning,
> 
> I get JOB_ID as well as JOB_RUN_ID in next way:
> 
> `args = getResolvedOptions(sys.argv, ['TempDir', 'JOB_NAME'])
> 
> print ">>>>> TempDir = " + args['TempDir']
> print ">>>>> JOB_NAME = " + args['JOB_NAME']
> print ">>>>> JOB_ID = " + args['JOB_ID'] # --> Implicit
> print ">>>>> JOB_RUN_ID = " + args['JOB_RUN_ID'] # --> Implicit`
> 
> As you can see, even though I have not included JOB_ID and JOB_RUN_ID, I'm getting implicity these values, and I can use them without any problem using args['JOB_ID'] and args['JOB_RUN_ID']
> 
> Hope this helps
> Mario

Yes it does have implicit parameters which always get parsed.. But the problem is not the absence of these parameters but a bug in parsing logic.. Please run the given test cases and you'll know what I mean..
