### ISSUE TITLE
No module named 'dynamicframe'

### ISSUE THREAD

**Issue by chitzinwin** [awslabs/aws-glue-libs#43]
I'm trying to import the GlueContext in gluepyshell using the line below;
`from awsglue.context import GlueContext`

But the following error persists:

```

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/mnt/c/Downloads/glue/aws-glue-libs-master/awsglue/__init__.py", line 13, in <module>
    from dynamicframe import DynamicFrame
ModuleNotFoundError: No module named 'dynamicframe'

```

**Comment by svajiraya** [comment]
Hi @chitzinwin,

Isn't it 

```
from awsglue.dynamicframe import DynamicFrame
```
??

**Comment by chitzinwin** [comment]
Same error for both since `GlueContext` also invoking the `awsglue.dynamicframe`.

However, the problem was solved when I called in WSL. Apparently, it is something to do with Windows environment/PATH.

**Comment by Abdulkalam98** [comment]
@chitzinwin  Could you please elobarate. How dii you fix these issue??.
I am also facing the same issue..

**Comment by chitzinwin** [comment]
@Abdulkalam98 , if you are in wsl2: try removing windows path:[https://gist.github.com/ilbunilcho/4280bd55a10cefef75e74986b6bff936]( https://gist.github.com/ilbunilcho/4280bd55a10cefef75e74986b6bff936)

 You still need to spin the cluster in local to use this python interface. As I said, dev-endpoint is the way to go.
