### ISSUE TITLE
Exception in thread "main" java.lang.NoSuchFieldError: ENDPOINT_OVERRIDDEN

### ISSUE THREAD

**Issue by cakkinep** [awslabs/aws-glue-libs#80]
I have built aws-glue-libs using the glue-1.0 branch.
Injected aws credentials into ~/.aws/credentials and launched spark-sql to test query AWS Glue data catalog.

I have last built the jars in December and they are still working, but the latest build is throwing following error.
Do we know if there are any bugs injected into aws-sdk which throws the following error?

spark-sql
21/03/09 21:04:49 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
log4j:WARN No appenders could be found for logger (org.apache.hadoop.conf.Configuration).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
Exception in thread "main" java.lang.NoSuchFieldError: ENDPOINT_OVERRIDDEN
	at com.amazonaws.services.glue.AWSGlueClient.executeGetDatabase(AWSGlueClient.java:4389)
	at com.amazonaws.services.glue.AWSGlueClient.getDatabase(AWSGlueClient.java:4371)
	at com.amazonaws.glue.catalog.metastore.AWSCatalogMetastoreClient.doesDefaultDBExist(AWSCatalogMetastoreClient.java:234)
	at com.amazonaws.glue.catalog.metastore.AWSCatalogMetastoreClient.<init>(AWSCatalogMetastoreClient.java:154)
	at com.amazonaws.glue.catalog.metastore.AWSGlueDataCatalogHiveClientFactory.createMetaStoreClient(AWSGlueDataCatalogHiveClientFactory.java:16)
	at org.apache.hadoop.hive.ql.metadata.Hive.createMetaStoreClient(Hive.java:3007)
	at org.apache.hadoop.hive.ql.metadata.Hive.getMSC(Hive.java:3042)
	at org.apache.hadoop.hive.ql.metadata.Hive.getAllDatabases(Hive.java:1235)
	at org.apache.hadoop.hive.ql.metadata.Hive.reloadFunctions(Hive.java:175)
	at org.apache.hadoop.hive.ql.metadata.Hive.<clinit>(Hive.java:167)
	at org.apache.hadoop.hive.ql.session.SessionState.start(SessionState.java:503)
	at org.apache.spark.sql.hive.thriftserver.SparkSQLCLIDriver$.main(SparkSQLCLIDriver.scala:133)
	at org.apache.spark.sql.hive.thriftserver.SparkSQLCLIDriver.main(SparkSQLCLIDriver.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.spark.deploy.JavaMainApplication.start(SparkApplication.scala:52)
	at org.apache.spark.deploy.SparkSubmit.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:849)
	at org.apache.spark.deploy.SparkSubmit.doRunMain$1(SparkSubmit.scala:167)
	at org.apache.spark.deploy.SparkSubmit.submit(SparkSubmit.scala:195)
	at org.apache.spark.deploy.SparkSubmit.doSubmit(SparkSubmit.scala:86)
	at org.apache.spark.deploy.SparkSubmit$$anon$2.doSubmit(SparkSubmit.scala:924)
	at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:933)
	at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)

**Comment by josie00** [comment]
Could you post the steps you built the jar? Let me try to reproduce this issue.

**Comment by Hari-Nagarajan** [comment]
I have the same issue, followed the exact steps outlined here: https://docs.aws.amazon.com/glue/latest/dg/aws-glue-programming-etl-libraries.html

**Comment by SimCo92** [comment]
Which version of JAVA are you using? @Hari-Nagarajan @cakkinep

**Comment by cakkinep** [comment]
> Which version of JAVA are you using? @Hari-Nagarajan @cakkinep
@SimCo92 
`java -version
openjdk version "1.8.0_282"
OpenJDK Runtime Environment (build 1.8.0_282-b08)
OpenJDK 64-Bit Server VM (build 25.282-b08, mixed mode)
`

**Comment by CedricPerotto** [comment]
Same Java version same issue, even it is only raised when running jobs with an AWS user that is not admin.

I had to tweak the pom.xml to get rid of this exception. See the pom.xml I used in attachment, to sum up the changes I made: 
  - exclude io.netty.netty-common,  io.netty.netty-buffer in AWSGlueETL 
  - force com.amazonaws.aws-java-sdk-glue and com.amazonaws.aws-java-sdk-lakeformation to 1.11.774 version

[pom.zip](https://github.com/awslabs/aws-glue-libs/files/6172591/pom.zip)

**Comment by cakkinep** [comment]
> Same Java version same issue, even it is only raised when running jobs with an AWS user that is not admin.
> 
> I had to tweak the pom.xml to get rid of this exception. See the pom.xml I used in attachment, to sum up the changes I made:
> 
> * exclude io.netty.netty-common,  io.netty.netty-buffer in AWSGlueETL
> * force com.amazonaws.aws-java-sdk-glue and com.amazonaws.aws-java-sdk-lakeformation to 1.11.774 version
> 
> [pom.zip](https://github.com/awslabs/aws-glue-libs/files/6172591/pom.zip)

@CedricPerotto this would only work if you already have 1.11.774 in your local maven from the past builds. 
A clean mvn build is not pulling down this version of aws-java-sdk-glue jar.

**Comment by mckenzig** [comment]
Hi same issue as reported by @Hari-Nagarajan

Follow instructions for glue 1.0 here:

https://github.com/awslabs/aws-glue-libs

 java --version
openjdk 11.0.10 2021-01-19
OpenJDK Runtime Environment (build 11.0.10+9-Ubuntu-0ubuntu1.20.04)
OpenJDK 64-Bit Server VM (build 11.0.10+9-Ubuntu-0ubuntu1.20.04, mixed mode, sharing)

python --version
Python 3.7.10

py4j.protocol.Py4JJavaError: An error occurred while calling o27.getCatalogSource.
: java.lang.NoSuchFieldError: ENDPOINT_OVERRIDDEN
        at com.amazonaws.services.glue.AWSGlueClient.executeGetTable(AWSGlueClient.java:6180)
        at com.amazonaws.services.glue.AWSGlueClient.getTable(AWSGlueClient.java:6162)
        at com.amazonaws.services.glue.util.DataCatalogWrapper$$anonfun$4.apply(DataCatalogWrapper.scala:139)
        at com.amazonaws.services.glue.util.DataCatalogWrapper$$anonfun$4.apply(DataCatalogWrapper.scala:135)
        at scala.util.Try$.apply(Try.scala:191)
        at com.amazonaws.services.glue.util.DataCatalogWrapper.getTable(DataCatalogWrapper.scala:135)
        at com.amazonaws.services.glue.GlueContext.getCatalogSource(GlueContext.scala:192)
        at com.amazonaws.services.glue.GlueContext.getCatalogSource(GlueContext.scala:181)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
        at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
        at py4j.Gateway.invoke(Gateway.java:282)
        at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
        at py4j.commands.CallCommand.execute(CallCommand.java:79)
        at py4j.GatewayConnection.run(GatewayConnection.java:238)
        at java.base/java.lang.Thread.run(Thread.java:834)

**Comment by mckenzig** [comment]
> Hi same issue as reported by @Hari-Nagarajan
> 
> Follow instructions for glue 1.0 here:
> 
> https://github.com/awslabs/aws-glue-libs
> 
> java --version
> openjdk 11.0.10 2021-01-19
> OpenJDK Runtime Environment (build 11.0.10+9-Ubuntu-0ubuntu1.20.04)
> OpenJDK 64-Bit Server VM (build 11.0.10+9-Ubuntu-0ubuntu1.20.04, mixed mode, sharing)
> 
> python --version
> Python 3.7.10
> 
> py4j.protocol.Py4JJavaError: An error occurred while calling o27.getCatalogSource.
> : java.lang.NoSuchFieldError: ENDPOINT_OVERRIDDEN
> at com.amazonaws.services.glue.AWSGlueClient.executeGetTable(AWSGlueClient.java:6180)
> at com.amazonaws.services.glue.AWSGlueClient.getTable(AWSGlueClient.java:6162)
> at com.amazonaws.services.glue.util.DataCatalogWrapper$$anonfun$4.apply(DataCatalogWrapper.scala:139)
> at com.amazonaws.services.glue.util.DataCatalogWrapper$$anonfun$4.apply(DataCatalogWrapper.scala:135)
> at scala.util.Try$.apply(Try.scala:191)
> at com.amazonaws.services.glue.util.DataCatalogWrapper.getTable(DataCatalogWrapper.scala:135)
> at com.amazonaws.services.glue.GlueContext.getCatalogSource(GlueContext.scala:192)
> at com.amazonaws.services.glue.GlueContext.getCatalogSource(GlueContext.scala:181)
> at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
> at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> at java.base/java.lang.reflect.Method.invoke(Method.java:566)
> at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
> at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
> at py4j.Gateway.invoke(Gateway.java:282)
> at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
> at py4j.commands.CallCommand.execute(CallCommand.java:79)
> at py4j.GatewayConnection.run(GatewayConnection.java:238)
> at java.base/java.lang.Thread.run(Thread.java:834)

fwiw, was able to get past this and run jobs by:

downgrading java to 1.8

sudo apt-get install openjdk-8-jdk
sudo update-alternatives --config java

And applying the changes in @CedricPerotto pom.xml

**Comment by github20170625** [comment]
i have the same issue
