### ISSUE TITLE
pyspark.sql.utils.IllegalArgumentException: u"Bucket name should not contain '_'"

### ISSUE THREAD

**Issue by seandavi** [awslabs/aws-glue-libs#9]
I am not sure at what level this problem occurs, but I had thought that '_' were allowed in bucket names? 

`glueContext.write_dynamic_frame.from_options(frame = expt_coll["experiment"], connection_type = "s3", connection_options = {"path": "s3://omics_metatata/temp_expt/"}, format = "parquet")`

Results in:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/mnt/tmp/spark-53bfe016-e87e-4fb9-90d8-bea9225887e0/userFiles-3c08fed2-db6b-495c-a4d3-918277ee71a7/PyGlue.zip/awsglue/dynamicframe.py", line 551, in from_options
  File "/mnt/tmp/spark-53bfe016-e87e-4fb9-90d8-bea9225887e0/userFiles-3c08fed2-db6b-495c-a4d3-918277ee71a7/PyGlue.zip/awsglue/context.py", line 176, in write_dynamic_frame_from_options
  File "/mnt/tmp/spark-53bfe016-e87e-4fb9-90d8-bea9225887e0/userFiles-3c08fed2-db6b-495c-a4d3-918277ee71a7/PyGlue.zip/awsglue/context.py", line 199, in write_from_options
  File "/mnt/tmp/spark-53bfe016-e87e-4fb9-90d8-bea9225887e0/userFiles-3c08fed2-db6b-495c-a4d3-918277ee71a7/PyGlue.zip/awsglue/data_sink.py", line 32, in write
  File "/mnt/tmp/spark-53bfe016-e87e-4fb9-90d8-bea9225887e0/userFiles-3c08fed2-db6b-495c-a4d3-918277ee71a7/PyGlue.zip/awsglue/data_sink.py", line 28, in writeFrame
  File "/usr/lib/spark/python/lib/py4j-0.10.4-src.zip/py4j/java_gateway.py", line 1133, in __call__
  File "/usr/lib/spark/python/pyspark/sql/utils.py", line 79, in deco
    raise IllegalArgumentException(s.split(': ', 1)[1], stackTrace)
pyspark.sql.utils.IllegalArgumentException: u"Bucket name should not contain '_'"
```

**Comment by villasv** [comment]
IIRC they should not. At least you can't create one using CloudFormation:

> **BucketName**
>    A name for the bucket. If you don't specify a name, AWS CloudFormation generates a unique physical ID and uses that ID for the bucket name. For more information, see Name Type. The bucket name must contain only lowercase letters, numbers, periods (.), and dashes (-). 

Source: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-s3-bucket.html#cfn-s3-bucket-name

**Comment by seandavi** [comment]
Thx, @villasv .
