### ISSUE TITLE
I can't use the regular parquet as a DynamicFrame format

### ISSUE THREAD

**Issue by fedsp** [awslabs/aws-glue-libs#95]
Hi, I'm pulling the current glue_libs_1.0.0_image_01 and working on a jupyter notebook on a docker container.

However, I know that locally I have some restrictions on using the "glueparquet format". But I got some erros running the following piece of code:

```
DataSink0.setFormat("parquet")
DataSink0.setCatalogInfo(catalogDatabase = database_name,catalogTableName = table_name)
DataSink0.writeFrame(tst_table)
```

This is the error that I receive:

```
An error was encountered:
An error occurred while calling o118.pyWriteDynamicFrame.
: java.lang.ClassNotFoundException: Failed to load format with name parquet
	at com.amazonaws.services.glue.util.ClassUtils$.loadByFullName(ClassUtils.scala:28)
	at com.amazonaws.services.glue.util.ClassUtils$.getClassByName(ClassUtils.scala:43)
	at com.amazonaws.services.glue.util.ClassUtils$.newInstanceByName(ClassUtils.scala:54)
	at com.amazonaws.services.glue.writers.DynamicRecordStreamWriter$.apply(DynamicRecordWriter.scala:106)
	at com.amazonaws.services.glue.sinks.HadoopDataSink.com$amazonaws$services$glue$sinks$HadoopDataSink$$checkSchema(HadoopDataSink.scala:109)
	at com.amazonaws.services.glue.sinks.HadoopDataSink$$anonfun$writeDynamicFrame$1.apply(HadoopDataSink.scala:157)
	at com.amazonaws.services.glue.sinks.HadoopDataSink$$anonfun$writeDynamicFrame$1.apply(HadoopDataSink.scala:141)
	at com.amazonaws.services.glue.util.FileSchemeWrapper$$anonfun$executeWithQualifiedScheme$1.apply(FileSchemeWrapper.scala:63)
	at com.amazonaws.services.glue.util.FileSchemeWrapper$$anonfun$executeWithQualifiedScheme$1.apply(FileSchemeWrapper.scala:63)
	at com.amazonaws.services.glue.util.FileSchemeWrapper.executeWith(FileSchemeWrapper.scala:57)
	at com.amazonaws.services.glue.util.FileSchemeWrapper.executeWithQualifiedScheme(FileSchemeWrapper.scala:63)
	at com.amazonaws.services.glue.sinks.HadoopDataSink.writeDynamicFrame(HadoopDataSink.scala:140)
	at com.amazonaws.services.glue.DataSink.pyWriteDynamicFrame(DataSink.scala:52)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
	at py4j.Gateway.invoke(Gateway.java:282)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.GatewayConnection.run(GatewayConnection.java:238)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.ClassNotFoundException: parquet
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at com.amazonaws.services.glue.util.ClassUtils$$anonfun$1.apply(ClassUtils.scala:25)
	at com.amazonaws.services.glue.util.ClassUtils$$anonfun$1.apply(ClassUtils.scala:25)
	at scala.util.Try$.apply(Try.scala:192)
	at com.amazonaws.services.glue.util.ClassUtils$.loadByFullName(ClassUtils.scala:25)
	... 23 more

Traceback (most recent call last):
  File "/home/aws-glue-libs/awsglue.zip/awsglue/data_sink.py", line 31, in writeFrame
    return DynamicFrame(self._jsink.pyWriteDynamicFrame(dynamic_frame._jdf, callsite(), info), dynamic_frame.glue_ctx, dynamic_frame.name + "_errors")
  File "/home/spark-2.4.3-bin-spark-2.4.3-bin-hadoop2.8/python/lib/py4j-0.10.7-src.zip/py4j/java_gateway.py", line 1257, in __call__
    answer, self.gateway_client, self.target_id, self.name)
  File "/home/spark-2.4.3-bin-spark-2.4.3-bin-hadoop2.8/python/lib/pyspark.zip/pyspark/sql/utils.py", line 63, in deco
    return f(*a, **kw)
  File "/home/spark-2.4.3-bin-spark-2.4.3-bin-hadoop2.8/python/lib/py4j-0.10.7-src.zip/py4j/protocol.py", line 328, in get_return_value
    format(target_id, ".", name), value)
py4j.protocol.Py4JJavaError: An error occurred while calling o118.pyWriteDynamicFrame.
: java.lang.ClassNotFoundException: Failed to load format with name parquet
	at com.amazonaws.services.glue.util.ClassUtils$.loadByFullName(ClassUtils.scala:28)
	at com.amazonaws.services.glue.util.ClassUtils$.getClassByName(ClassUtils.scala:43)
	at com.amazonaws.services.glue.util.ClassUtils$.newInstanceByName(ClassUtils.scala:54)
	at com.amazonaws.services.glue.writers.DynamicRecordStreamWriter$.apply(DynamicRecordWriter.scala:106)
	at com.amazonaws.services.glue.sinks.HadoopDataSink.com$amazonaws$services$glue$sinks$HadoopDataSink$$checkSchema(HadoopDataSink.scala:109)
	at com.amazonaws.services.glue.sinks.HadoopDataSink$$anonfun$writeDynamicFrame$1.apply(HadoopDataSink.scala:157)
	at com.amazonaws.services.glue.sinks.HadoopDataSink$$anonfun$writeDynamicFrame$1.apply(HadoopDataSink.scala:141)
	at com.amazonaws.services.glue.util.FileSchemeWrapper$$anonfun$executeWithQualifiedScheme$1.apply(FileSchemeWrapper.scala:63)
	at com.amazonaws.services.glue.util.FileSchemeWrapper$$anonfun$executeWithQualifiedScheme$1.apply(FileSchemeWrapper.scala:63)
	at com.amazonaws.services.glue.util.FileSchemeWrapper.executeWith(FileSchemeWrapper.scala:57)
	at com.amazonaws.services.glue.util.FileSchemeWrapper.executeWithQualifiedScheme(FileSchemeWrapper.scala:63)
	at com.amazonaws.services.glue.sinks.HadoopDataSink.writeDynamicFrame(HadoopDataSink.scala:140)
	at com.amazonaws.services.glue.DataSink.pyWriteDynamicFrame(DataSink.scala:52)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
	at py4j.Gateway.invoke(Gateway.java:282)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.GatewayConnection.run(GatewayConnection.java:238)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.ClassNotFoundException: parquet
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at com.amazonaws.services.glue.util.ClassUtils$$anonfun$1.apply(ClassUtils.scala:25)
	at com.amazonaws.services.glue.util.ClassUtils$$anonfun$1.apply(ClassUtils.scala:25)
	at scala.util.Try$.apply(Try.scala:192)
	at com.amazonaws.services.glue.util.ClassUtils$.loadByFullName(ClassUtils.scala:25)
	... 23 more
```

**Comment by svajiraya** [comment]
Hi @fedsp 

I was able to replicate this on my end. Based on the 3rd bullet point in [documentation[(https://docs.aws.amazon.com/glue/latest/dg/update-from-job.html#update-from-job-restrictions) - this is the expected behaviour. 


- To create or update tables with the parquet classification, you must utilize the AWS Glue optimized parquet writer for DynamicFrames. This can be achieved in one of three ways:
    - Call write_dynamic_frame_from_catalog(), then set a useGlueParquetWriter table property to true in the table you are updating.
    - Call getSink() in your script with connection_type="s3", then set your format to glueparquet.
    - Call getSink() in your script with connection_type="s3", then set your format to parquet and pass a useGlueParquetWriter property as true in your format_options, this is especially useful for creating new parquet tables.


Since `glueparquet` is not supported in local development environment, you will not be able to test `enableUpdateCatalog` feature to create table with `parquet` classification from local/docker image.

**Comment by fedsp** [comment]
Got it. For local testing purposes I can give up the update catalog feature.

However, when I change the datasink parameter "glueparquet" to "parquet" I got the following error:

```
An error was encountered:
An error occurred while calling o179.pyWriteDynamicFrame.
: java.lang.ClassNotFoundException: Failed to load format with name parquet
	at com.amazonaws.services.glue.util.ClassUtils$.loadByFullName(ClassUtils.scala:28)
	at com.amazonaws.services.glue.util.ClassUtils$.getClassByName(ClassUtils.scala:43)
	at com.amazonaws.services.glue.util.ClassUtils$.newInstanceByName(ClassUtils.scala:54)
	at com.amazonaws.services.glue.writers.DynamicRecordStreamWriter$.apply(DynamicRecordWriter.scala:106)
	at com.amazonaws.services.glue.sinks.HadoopDataSink.com$amazonaws$services$glue$sinks$HadoopDataSink$$checkSchema(HadoopDataSink.scala:109)
	at com.amazonaws.services.glue.sinks.HadoopDataSink$$anonfun$writeDynamicFrame$1.apply(HadoopDataSink.scala:157)
	at com.amazonaws.services.glue.sinks.HadoopDataSink$$anonfun$writeDynamicFrame$1.apply(HadoopDataSink.scala:141)
	at com.amazonaws.services.glue.util.FileSchemeWrapper$$anonfun$executeWithQualifiedScheme$1.apply(FileSchemeWrapper.scala:63)
	at com.amazonaws.services.glue.util.FileSchemeWrapper$$anonfun$executeWithQualifiedScheme$1.apply(FileSchemeWrapper.scala:63)
	at com.amazonaws.services.glue.util.FileSchemeWrapper.executeWith(FileSchemeWrapper.scala:57)
	at com.amazonaws.services.glue.util.FileSchemeWrapper.executeWithQualifiedScheme(FileSchemeWrapper.scala:63)
	at com.amazonaws.services.glue.sinks.HadoopDataSink.writeDynamicFrame(HadoopDataSink.scala:140)
	at com.amazonaws.services.glue.DataSink.pyWriteDynamicFrame(DataSink.scala:52)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
	at py4j.Gateway.invoke(Gateway.java:282)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.GatewayConnection.run(GatewayConnection.java:238)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.ClassNotFoundException: parquet
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at com.amazonaws.services.glue.util.ClassUtils$$anonfun$1.apply(ClassUtils.scala:25)
	at com.amazonaws.services.glue.util.ClassUtils$$anonfun$1.apply(ClassUtils.scala:25)
	at scala.util.Try$.apply(Try.scala:192)
	at com.amazonaws.services.glue.util.ClassUtils$.loadByFullName(ClassUtils.scala:25)
	... 23 more

Traceback (most recent call last):
  File "/home/aws-glue-libs/awsglue.zip/awsglue/data_sink.py", line 31, in writeFrame
    return DynamicFrame(self._jsink.pyWriteDynamicFrame(dynamic_frame._jdf, callsite(), info), dynamic_frame.glue_ctx, dynamic_frame.name + "_errors")
  File "/home/spark-2.4.3-bin-spark-2.4.3-bin-hadoop2.8/python/lib/py4j-0.10.7-src.zip/py4j/java_gateway.py", line 1257, in __call__
    answer, self.gateway_client, self.target_id, self.name)
  File "/home/spark-2.4.3-bin-spark-2.4.3-bin-hadoop2.8/python/lib/pyspark.zip/pyspark/sql/utils.py", line 63, in deco
    return f(*a, **kw)
  File "/home/spark-2.4.3-bin-spark-2.4.3-bin-hadoop2.8/python/lib/py4j-0.10.7-src.zip/py4j/protocol.py", line 328, in get_return_value
    format(target_id, ".", name), value)
py4j.protocol.Py4JJavaError: An error occurred while calling o179.pyWriteDynamicFrame.
: java.lang.ClassNotFoundException: Failed to load format with name parquet
	at com.amazonaws.services.glue.util.ClassUtils$.loadByFullName(ClassUtils.scala:28)
	at com.amazonaws.services.glue.util.ClassUtils$.getClassByName(ClassUtils.scala:43)
	at com.amazonaws.services.glue.util.ClassUtils$.newInstanceByName(ClassUtils.scala:54)
	at com.amazonaws.services.glue.writers.DynamicRecordStreamWriter$.apply(DynamicRecordWriter.scala:106)
	at com.amazonaws.services.glue.sinks.HadoopDataSink.com$amazonaws$services$glue$sinks$HadoopDataSink$$checkSchema(HadoopDataSink.scala:109)
	at com.amazonaws.services.glue.sinks.HadoopDataSink$$anonfun$writeDynamicFrame$1.apply(HadoopDataSink.scala:157)
	at com.amazonaws.services.glue.sinks.HadoopDataSink$$anonfun$writeDynamicFrame$1.apply(HadoopDataSink.scala:141)
	at com.amazonaws.services.glue.util.FileSchemeWrapper$$anonfun$executeWithQualifiedScheme$1.apply(FileSchemeWrapper.scala:63)
	at com.amazonaws.services.glue.util.FileSchemeWrapper$$anonfun$executeWithQualifiedScheme$1.apply(FileSchemeWrapper.scala:63)
	at com.amazonaws.services.glue.util.FileSchemeWrapper.executeWith(FileSchemeWrapper.scala:57)
	at com.amazonaws.services.glue.util.FileSchemeWrapper.executeWithQualifiedScheme(FileSchemeWrapper.scala:63)
	at com.amazonaws.services.glue.sinks.HadoopDataSink.writeDynamicFrame(HadoopDataSink.scala:140)
	at com.amazonaws.services.glue.DataSink.pyWriteDynamicFrame(DataSink.scala:52)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
	at py4j.Gateway.invoke(Gateway.java:282)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.GatewayConnection.run(GatewayConnection.java:238)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.ClassNotFoundException: parquet
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at com.amazonaws.services.glue.util.ClassUtils$$anonfun$1.apply(ClassUtils.scala:25)
	at com.amazonaws.services.glue.util.ClassUtils$$anonfun$1.apply(ClassUtils.scala:25)
	at scala.util.Try$.apply(Try.scala:192)
	at com.amazonaws.services.glue.util.ClassUtils$.loadByFullName(ClassUtils.scala:25)
	... 23 more
```

**Comment by svajiraya** [comment]
@fedsp You are correct. As mentioned earlier, this is expected. `DataSink` class will not recognise built-in parquet writer (`DataSink` class can only recognise `AWS Glue optimized parquet writer` for parquet writes). You will see the same behavior if you run it as AWS Glue job. 

> Ref: To create or update tables with the parquet classification, you must utilize the **AWS Glue optimized parquet writer** for DynamicFrame

Considering this, you will not be able to use `DataSink` class locally for parquet writes at all.

**Comment by fedsp** [comment]
Now we are using standard SQL statements to create the tables.
